version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx/conf.d:/etc/nginx/conf.d/
        depends_on:
            - app
        container_name: app-nginx
    app:
        build:
            context: .
            dockerfile: docker-compose/app/Dockerfile
        image: php:8.2-fpm
        volumes:
            - ./:/var/www
        container_name: app
